In [176]:
from scipy.optimize import linear_sum_assignment
import numpy as np

In [177]:
cost = np.round(10 * np.random.rand(4, 3, 3), 0)
cost

array([[[  0.,   4.,   8.],
        [ 10.,   3.,   7.],
        [  6.,   5.,   0.]],

       [[  7.,   7.,   6.],
        [  5.,   3.,   9.],
        [  5.,   9.,   0.]],

       [[  6.,   9.,   2.],
        [  0.,   3.,   7.],
        [  6.,   2.,   8.]],

       [[  9.,   9.,   2.],
        [  7.,   7.,   5.],
        [  8.,   4.,   8.]]])

In [178]:
u = [.5] * cost.shape[0]
cost1 = np.copy(cost)
ub = 1000
lb = -1000
l = .9
print('initial cost\n', cost)
print('------')

for cnt in range(0, 2):
    cost1 = np.copy(cost)
    print('u', u)
    for k in range(0, cost.shape[0]):
        cost1[k,:,:] = cost[k,:,:] - u[k]

    print('cost1 - planar reduced\n', cost1)
    w = np.max(cost1, axis=0)
    h = np.argmax(cost1, axis=0)
    print('arg max in w\n', h)
    print('w\n', w)
    
    row, col = linear_sum_assignment(-w)
    print('sum:', w[row, col].sum(), '\nassignment:', list(zip(row, col)))
    phi = w[row, col].sum() + np.sum(u)
    print('phi:', phi)
    
    ksi = list(zip(h[row, col], row, col))
    print('ksi', ksi)
    ksi_ar = np.array(ksi)
    ksi_sum = np.sum([cost[x] for x in ksi])
    print('ksi sum', ksi_sum)
    
    ub = np.min([ub, phi])
    lb = np.max([lb, ksi_sum])
    print('ub, lb', ub, lb)
    
    nu = [0] * cost.shape[0]
    for x in ksi_ar[:,0]:
        nu[x] = nu[x] + 1
    nu = 1 - np.array(nu)    
    print('nu', nu)
    
    sigma = l * (phi - lb) / (np.linalg.norm(nu) ** 2)
    u = np.array([0] * cost.shape[0])
    u = u + sigma * np.array(nu)
    print('new u', u)    
    print('-------')

initial cost
 [[[  0.   4.   8.]
  [ 10.   3.   7.]
  [  6.   5.   0.]]

 [[  7.   7.   6.]
  [  5.   3.   9.]
  [  5.   9.   0.]]

 [[  6.   9.   2.]
  [  0.   3.   7.]
  [  6.   2.   8.]]

 [[  9.   9.   2.]
  [  7.   7.   5.]
  [  8.   4.   8.]]]
------
u [0.5, 0.5, 0.5, 0.5]
cost1 - planar reduced
 [[[-0.5  3.5  7.5]
  [ 9.5  2.5  6.5]
  [ 5.5  4.5 -0.5]]

 [[ 6.5  6.5  5.5]
  [ 4.5  2.5  8.5]
  [ 4.5  8.5 -0.5]]

 [[ 5.5  8.5  1.5]
  [-0.5  2.5  6.5]
  [ 5.5  1.5  7.5]]

 [[ 8.5  8.5  1.5]
  [ 6.5  6.5  4.5]
  [ 7.5  3.5  7.5]]]
arg max in w
 [[3 2 0]
 [0 3 1]
 [3 1 2]]
w
 [[ 8.5  8.5  7.5]
 [ 9.5  6.5  8.5]
 [ 7.5  8.5  7.5]]
sum: 25.5 
assignment: [(0, 2), (1, 0), (2, 1)]
phi: 27.5
ksi [(0, 0, 2), (0, 1, 0), (1, 2, 1)]
ksi sum 27.0
ub, lb 27.5 27.0
nu [-1  0  1  1]
new u [-0.15  0.    0.15  0.15]
-------
u [-0.15  0.    0.15  0.15]
cost1 - planar reduced
 [[[  0.15   4.15   8.15]
  [ 10.15   3.15   7.15]
  [  6.15   5.15   0.15]]

 [[  7.     7.     6.  ]
  [  5.     3.     9.  

In [185]:
ksi_ar[:,1:]

array([[0, 2],
       [1, 0],
       [2, 1]], dtype=int64)

In [186]:
cost

array([[[  0.,   4.,   8.],
        [ 10.,   3.,   7.],
        [  6.,   5.,   0.]],

       [[  7.,   7.,   6.],
        [  5.,   3.,   9.],
        [  5.,   9.,   0.]],

       [[  6.,   9.,   2.],
        [  0.,   3.,   7.],
        [  6.,   2.,   8.]],

       [[  9.,   9.,   2.],
        [  7.,   7.,   5.],
        [  8.,   4.,   8.]]])

In [211]:
ar = np.vstack([cost[:,0,2], cost[:,1,0], cost[:,2,1]])
r, c = linear_sum_assignment(-ar)
print(ar)
np.array(list(zip(r, c)))[:,1]

[[  8.   6.   2.   2.]
 [ 10.   5.   0.   7.]
 [  5.   9.   2.   4.]]


array([0, 3, 1], dtype=int64)